/*
 * Phrase Strings API Reference
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@phrase.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.phrase.client.api;

import com.phrase.client.ApiException;
import com.phrase.client.model.BitbucketSync;
import com.phrase.client.model.BitbucketSyncExportParameters;
import com.phrase.client.model.BitbucketSyncExportResponse;
import com.phrase.client.model.BitbucketSyncImportParameters;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for BitbucketSyncApi
 */
@Ignore
public class BitbucketSyncApiTest {

    private final BitbucketSyncApi api = new BitbucketSyncApi();

    
    /**
     * Export from Phrase Strings to Bitbucket
     *
     * Export translations from Phrase Strings to Bitbucket according to the .phraseapp.yml file within the Bitbucket Repository. &lt;br&gt;&lt;br&gt;&lt;i&gt;Note: Export is done asynchronously and may take several seconds depending on the project size.&lt;/i&gt;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void bitbucketSyncExportTest() throws ApiException {
        String id = null;
        BitbucketSyncExportParameters bitbucketSyncExportParameters = null;
        String xPhraseAppOTP = null;
        BitbucketSyncExportResponse response = api.bitbucketSyncExport(id, bitbucketSyncExportParameters, xPhraseAppOTP);

        // TODO: test validations
    }
    
    /**
     * Import to Phrase Strings from Bitbucket
     *
     * Import translations from Bitbucket to Phrase Strings according to the .phraseapp.yml file within the Bitbucket repository. &lt;br&gt;&lt;br&gt;&lt;i&gt;Note: Import is done asynchronously and may take several seconds depending on the project size.&lt;/i&gt;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void bitbucketSyncImportTest() throws ApiException {
        String id = null;
        BitbucketSyncImportParameters bitbucketSyncImportParameters = null;
        String xPhraseAppOTP = null;
        api.bitbucketSyncImport(id, bitbucketSyncImportParameters, xPhraseAppOTP);

        // TODO: test validations
    }
    
    /**
     * List Bitbucket syncs
     *
     * List all Bitbucket repositories for which synchronisation with Phrase Strings is activated.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void bitbucketSyncsListTest() throws ApiException {
        String xPhraseAppOTP = null;
        String accountId = null;
        List<BitbucketSync> response = api.bitbucketSyncsList(xPhraseAppOTP, accountId);

        // TODO: test validations
    }
    
}
