/*
 * Phrase API Reference
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@phrase.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.phrase.client.api;

import com.phrase.client.ApiException;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TermBaseTranslationApi
 */
@Ignore
public class TermBaseTranslationApiTest {

    private final TermBaseTranslationApi api = new TermBaseTranslationApi();

    
    /**
     * Delete a translation for a term
     *
     * Delete an existing translation of a term in a term base (previously: glossary).
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void glossaryTermTranslationDeleteTest() throws ApiException {
        String accountId = null;
        String glossaryId = null;
        String termId = null;
        String id = null;
        String xPhraseAppOTP = null;
        api.glossaryTermTranslationDelete(accountId, glossaryId, termId, id, xPhraseAppOTP);

        // TODO: test validations
    }
    
}
