/*
 * Phrase API Reference
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@phrase.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.phrase.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.phrase.client.model.ProjectShort;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.threeten.bp.OffsetDateTime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for BitbucketSync
 */
public class BitbucketSyncTest {
    private final BitbucketSync model = new BitbucketSync();

    /**
     * Model tests for BitbucketSync
     */
    @Test
    public void testBitbucketSync() {
        // TODO: test BitbucketSync
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'repositoryName'
     */
    @Test
    public void repositoryNameTest() {
        // TODO: test repositoryName
    }

    /**
     * Test the property 'lastExportToBitbucketAt'
     */
    @Test
    public void lastExportToBitbucketAtTest() {
        // TODO: test lastExportToBitbucketAt
    }

    /**
     * Test the property 'lastImportFromBitbucketAt'
     */
    @Test
    public void lastImportFromBitbucketAtTest() {
        // TODO: test lastImportFromBitbucketAt
    }

    /**
     * Test the property 'validPhraseappYaml'
     */
    @Test
    public void validPhraseappYamlTest() {
        // TODO: test validPhraseappYaml
    }

    /**
     * Test the property 'phraseappProjects'
     */
    @Test
    public void phraseappProjectsTest() {
        // TODO: test phraseappProjects
    }

}
