/*
 * Phrase Strings API Reference
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@phrase.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.phrase.client.model;

import com.google.gson.annotations.SerializedName;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for CustomMetadataDataType
 */
public class CustomMetadataDataTypeTest {
    /**
     * Model tests for CustomMetadataDataType
     */
    @Test
    public void testCustomMetadataDataType() {
        // TODO: test CustomMetadataDataType
    }

}
