/*
 * Phrase API Reference
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@phrase.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.phrase.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for GitlabSync
 */
public class GitlabSyncTest {
    private final GitlabSync model = new GitlabSync();

    /**
     * Model tests for GitlabSync
     */
    @Test
    public void testGitlabSync() {
        // TODO: test GitlabSync
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'projectId'
     */
    @Test
    public void projectIdTest() {
        // TODO: test projectId
    }

    /**
     * Test the property 'gitlabProjectId'
     */
    @Test
    public void gitlabProjectIdTest() {
        // TODO: test gitlabProjectId
    }

    /**
     * Test the property 'gitlabBranchName'
     */
    @Test
    public void gitlabBranchNameTest() {
        // TODO: test gitlabBranchName
    }

    /**
     * Test the property 'autoImport'
     */
    @Test
    public void autoImportTest() {
        // TODO: test autoImport
    }

    /**
     * Test the property 'autoImportSecret'
     */
    @Test
    public void autoImportSecretTest() {
        // TODO: test autoImportSecret
    }

    /**
     * Test the property 'autoImportUrl'
     */
    @Test
    public void autoImportUrlTest() {
        // TODO: test autoImportUrl
    }

    /**
     * Test the property 'selfHostedApiUrl'
     */
    @Test
    public void selfHostedApiUrlTest() {
        // TODO: test selfHostedApiUrl
    }

    /**
     * Test the property 'lastExportedAt'
     */
    @Test
    public void lastExportedAtTest() {
        // TODO: test lastExportedAt
    }

    /**
     * Test the property 'lastImportedAt'
     */
    @Test
    public void lastImportedAtTest() {
        // TODO: test lastImportedAt
    }

    /**
     * Test the property 'lastStatus'
     */
    @Test
    public void lastStatusTest() {
        // TODO: test lastStatus
    }

}
