/*
 * Phrase API Reference
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@phrase.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.phrase.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.phrase.client.model.KeyPreview;
import com.phrase.client.model.LocalePreview;
import com.phrase.client.model.UserPreview;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for JobDetails1
 */
public class JobDetails1Test {
    private final JobDetails1 model = new JobDetails1();

    /**
     * Model tests for JobDetails1
     */
    @Test
    public void testJobDetails1() {
        // TODO: test JobDetails1
    }

    /**
     * Test the property 'owner'
     */
    @Test
    public void ownerTest() {
        // TODO: test owner
    }

    /**
     * Test the property 'jobTagName'
     */
    @Test
    public void jobTagNameTest() {
        // TODO: test jobTagName
    }

    /**
     * Test the property 'sourceLocale'
     */
    @Test
    public void sourceLocaleTest() {
        // TODO: test sourceLocale
    }

    /**
     * Test the property 'locales'
     */
    @Test
    public void localesTest() {
        // TODO: test locales
    }

    /**
     * Test the property 'keys'
     */
    @Test
    public void keysTest() {
        // TODO: test keys
    }

}
