/*
 * Phrase Strings API Reference
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@phrase.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.phrase.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for KeyPreview
 */
public class KeyPreviewTest {
    private final KeyPreview model = new KeyPreview();

    /**
     * Model tests for KeyPreview
     */
    @Test
    public void testKeyPreview() {
        // TODO: test KeyPreview
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'plural'
     */
    @Test
    public void pluralTest() {
        // TODO: test plural
    }

    /**
     * Test the property 'useOrdinalRules'
     */
    @Test
    public void useOrdinalRulesTest() {
        // TODO: test useOrdinalRules
    }

}
