/*
 * Phrase API Reference
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@phrase.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.phrase.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for LocaleCreateParameters
 */
public class LocaleCreateParametersTest {
    private final LocaleCreateParameters model = new LocaleCreateParameters();

    /**
     * Model tests for LocaleCreateParameters
     */
    @Test
    public void testLocaleCreateParameters() {
        // TODO: test LocaleCreateParameters
    }

    /**
     * Test the property 'branch'
     */
    @Test
    public void branchTest() {
        // TODO: test branch
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'code'
     */
    @Test
    public void codeTest() {
        // TODO: test code
    }

    /**
     * Test the property '_default'
     */
    @Test
    public void _defaultTest() {
        // TODO: test _default
    }

    /**
     * Test the property 'main'
     */
    @Test
    public void mainTest() {
        // TODO: test main
    }

    /**
     * Test the property 'rtl'
     */
    @Test
    public void rtlTest() {
        // TODO: test rtl
    }

    /**
     * Test the property 'sourceLocaleId'
     */
    @Test
    public void sourceLocaleIdTest() {
        // TODO: test sourceLocaleId
    }

    /**
     * Test the property 'unverifyNewTranslations'
     */
    @Test
    public void unverifyNewTranslationsTest() {
        // TODO: test unverifyNewTranslations
    }

    /**
     * Test the property 'unverifyUpdatedTranslations'
     */
    @Test
    public void unverifyUpdatedTranslationsTest() {
        // TODO: test unverifyUpdatedTranslations
    }

    /**
     * Test the property 'autotranslate'
     */
    @Test
    public void autotranslateTest() {
        // TODO: test autotranslate
    }

}
