/*
 * Phrase Strings API Reference
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@phrase.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.phrase.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.phrase.client.model.Error;
import com.phrase.client.model.ErrorError;
import com.phrase.client.model.ProjectsQualityPerformanceScore200ResponseAnyOf;
import com.phrase.client.model.ProjectsQualityPerformanceScore200ResponseAnyOfData;
import com.phrase.client.model.ProjectsQualityPerformanceScore200ResponseAnyOfErrorsInner;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ProjectsQualityPerformanceScore200Response
 */
public class ProjectsQualityPerformanceScore200ResponseTest {
    private final ProjectsQualityPerformanceScore200Response model = new ProjectsQualityPerformanceScore200Response();

    /**
     * Model tests for ProjectsQualityPerformanceScore200Response
     */
    @Test
    public void testProjectsQualityPerformanceScore200Response() {
        // TODO: test ProjectsQualityPerformanceScore200Response
    }

    /**
     * Test the property 'error'
     */
    @Test
    public void errorTest() {
        // TODO: test error
    }

    /**
     * Test the property 'data'
     */
    @Test
    public void dataTest() {
        // TODO: test data
    }

    /**
     * Test the property 'errors'
     */
    @Test
    public void errorsTest() {
        // TODO: test errors
    }

}
