/*
 * Phrase Strings API Reference
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@phrase.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.phrase.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.phrase.client.model.Account;
import com.phrase.client.model.Space1;
import com.phrase.client.model.UserPreview;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ProjectDetails
 */
public class ProjectDetailsTest {
    private final ProjectDetails model = new ProjectDetails();

    /**
     * Model tests for ProjectDetails
     */
    @Test
    public void testProjectDetails() {
        // TODO: test ProjectDetails
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'slug'
     */
    @Test
    public void slugTest() {
        // TODO: test slug
    }

    /**
     * Test the property 'mainFormat'
     */
    @Test
    public void mainFormatTest() {
        // TODO: test mainFormat
    }

    /**
     * Test the property 'projectImageUrl'
     */
    @Test
    public void projectImageUrlTest() {
        // TODO: test projectImageUrl
    }

    /**
     * Test the property 'media'
     */
    @Test
    public void mediaTest() {
        // TODO: test media
    }

    /**
     * Test the property 'account'
     */
    @Test
    public void accountTest() {
        // TODO: test account
    }

    /**
     * Test the property 'space'
     */
    @Test
    public void spaceTest() {
        // TODO: test space
    }

    /**
     * Test the property 'pointOfContact'
     */
    @Test
    public void pointOfContactTest() {
        // TODO: test pointOfContact
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    public void updatedAtTest() {
        // TODO: test updatedAt
    }

    /**
     * Test the property 'sharesTranslationMemory'
     */
    @Test
    public void sharesTranslationMemoryTest() {
        // TODO: test sharesTranslationMemory
    }

    /**
     * Test the property 'machineTranslationEnabled'
     */
    @Test
    public void machineTranslationEnabledTest() {
        // TODO: test machineTranslationEnabled
    }

    /**
     * Test the property 'zeroPluralFormEnabled'
     */
    @Test
    public void zeroPluralFormEnabledTest() {
        // TODO: test zeroPluralFormEnabled
    }

    /**
     * Test the property 'enableAllDataTypeTranslationKeysForTranslators'
     */
    @Test
    public void enableAllDataTypeTranslationKeysForTranslatorsTest() {
        // TODO: test enableAllDataTypeTranslationKeysForTranslators
    }

    /**
     * Test the property 'enableIcuMessageFormat'
     */
    @Test
    public void enableIcuMessageFormatTest() {
        // TODO: test enableIcuMessageFormat
    }

    /**
     * Test the property 'enableBranching'
     */
    @Test
    public void enableBranchingTest() {
        // TODO: test enableBranching
    }

    /**
     * Test the property 'protectMasterBranch'
     */
    @Test
    public void protectMasterBranchTest() {
        // TODO: test protectMasterBranch
    }

    /**
     * Test the property 'autotranslateEnabled'
     */
    @Test
    public void autotranslateEnabledTest() {
        // TODO: test autotranslateEnabled
    }

    /**
     * Test the property 'autotranslateCheckNewTranslationKeys'
     */
    @Test
    public void autotranslateCheckNewTranslationKeysTest() {
        // TODO: test autotranslateCheckNewTranslationKeys
    }

    /**
     * Test the property 'autotranslateCheckNewUploads'
     */
    @Test
    public void autotranslateCheckNewUploadsTest() {
        // TODO: test autotranslateCheckNewUploads
    }

    /**
     * Test the property 'autotranslateCheckNewLocales'
     */
    @Test
    public void autotranslateCheckNewLocalesTest() {
        // TODO: test autotranslateCheckNewLocales
    }

    /**
     * Test the property 'autotranslateMarkAsUnverified'
     */
    @Test
    public void autotranslateMarkAsUnverifiedTest() {
        // TODO: test autotranslateMarkAsUnverified
    }

    /**
     * Test the property 'autotranslateUseMachineTranslation'
     */
    @Test
    public void autotranslateUseMachineTranslationTest() {
        // TODO: test autotranslateUseMachineTranslation
    }

    /**
     * Test the property 'autotranslateUseTranslationMemory'
     */
    @Test
    public void autotranslateUseTranslationMemoryTest() {
        // TODO: test autotranslateUseTranslationMemory
    }

    /**
     * Test the property 'defaultEncoding'
     */
    @Test
    public void defaultEncodingTest() {
        // TODO: test defaultEncoding
    }

}
