/*
 * Phrase Strings API Reference
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@phrase.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.phrase.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.phrase.client.model.Account;
import com.phrase.client.model.Project;
import com.phrase.client.model.ProjectDetails1;
import com.phrase.client.model.Space1;
import com.phrase.client.model.UserPreview;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ProjectDetails
 */
public class ProjectDetailsTest {
    private final ProjectDetails model = new ProjectDetails();

    /**
     * Model tests for ProjectDetails
     */
    @Test
    public void testProjectDetails() {
        // TODO: test ProjectDetails
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'slug'
     */
    @Test
    public void slugTest() {
        // TODO: test slug
    }

    /**
     * Test the property 'mainFormat'
     */
    @Test
    public void mainFormatTest() {
        // TODO: test mainFormat
    }

    /**
     * Test the property 'projectImageUrl'
     */
    @Test
    public void projectImageUrlTest() {
        // TODO: test projectImageUrl
    }

    /**
     * Test the property 'media'
     */
    @Test
    public void mediaTest() {
        // TODO: test media
    }

    /**
     * Test the property 'account'
     */
    @Test
    public void accountTest() {
        // TODO: test account
    }

    /**
     * Test the property 'space'
     */
    @Test
    public void spaceTest() {
        // TODO: test space
    }

    /**
     * Test the property 'pointOfContact'
     */
    @Test
    public void pointOfContactTest() {
        // TODO: test pointOfContact
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    public void updatedAtTest() {
        // TODO: test updatedAt
    }

    /**
     * Test the property 'sharesTranslationMemory'
     */
    @Test
    public void sharesTranslationMemoryTest() {
        // TODO: test sharesTranslationMemory
    }

}
