/*
 * Phrase Strings API Reference
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@phrase.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.phrase.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ReleaseUpdateParameters1
 */
public class ReleaseUpdateParameters1Test {
    private final ReleaseUpdateParameters1 model = new ReleaseUpdateParameters1();

    /**
     * Model tests for ReleaseUpdateParameters1
     */
    @Test
    public void testReleaseUpdateParameters1() {
        // TODO: test ReleaseUpdateParameters1
    }

    /**
     * Test the property 'cronSchedule'
     */
    @Test
    public void cronScheduleTest() {
        // TODO: test cronSchedule
    }

    /**
     * Test the property 'timeZone'
     */
    @Test
    public void timeZoneTest() {
        // TODO: test timeZone
    }

    /**
     * Test the property 'localeIds'
     */
    @Test
    public void localeIdsTest() {
        // TODO: test localeIds
    }

    /**
     * Test the property 'tags'
     */
    @Test
    public void tagsTest() {
        // TODO: test tags
    }

    /**
     * Test the property 'branch'
     */
    @Test
    public void branchTest() {
        // TODO: test branch
    }

    /**
     * Test the property 'appMinVersion'
     */
    @Test
    public void appMinVersionTest() {
        // TODO: test appMinVersion
    }

    /**
     * Test the property 'appMaxVersion'
     */
    @Test
    public void appMaxVersionTest() {
        // TODO: test appMaxVersion
    }

}
