/*
 * Phrase Strings API Reference
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@phrase.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.phrase.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.phrase.client.model.ProjectShort;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for RepoSync
 */
public class RepoSyncTest {
    private final RepoSync model = new RepoSync();

    /**
     * Model tests for RepoSync
     */
    @Test
    public void testRepoSync() {
        // TODO: test RepoSync
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'project'
     */
    @Test
    public void projectTest() {
        // TODO: test project
    }

    /**
     * Test the property 'provider'
     */
    @Test
    public void providerTest() {
        // TODO: test provider
    }

    /**
     * Test the property 'enabled'
     */
    @Test
    public void enabledTest() {
        // TODO: test enabled
    }

    /**
     * Test the property 'autoImport'
     */
    @Test
    public void autoImportTest() {
        // TODO: test autoImport
    }

    /**
     * Test the property 'repoName'
     */
    @Test
    public void repoNameTest() {
        // TODO: test repoName
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'lastImportAt'
     */
    @Test
    public void lastImportAtTest() {
        // TODO: test lastImportAt
    }

    /**
     * Test the property 'lastExportAt'
     */
    @Test
    public void lastExportAtTest() {
        // TODO: test lastExportAt
    }

}
