name: release

on:
  push:
    branches:
      - scd-402-fix-publish

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '8' ]
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --no-transfer-progress --file pom.xml

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.14.3
      -
        name: Install GPG key
        id: install-gpg-key
        run: |
          # Install gpg secret key
          cat <(echo -e "${{ secrets.GPG_KEY }}") | gpg --batch --import
      -
        name: Release Package
        run: bash ./.github/workflows/release.sh -xe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: 3.8.0
          OSSRH_USER: "${{ secrets.OSSRH_USER }}"
          OSSRH_PASSWORD: "${{ secrets.OSSRH_PASSWORD }}"
